- id: '1693627516230'
  description: tesla charge indicator update on state change
  trigger:
  - platform: state
    entity_id:
    - sensor.tesla_wall_connector_state
  condition: []
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: sensor.tesla_wall_connector_state
        state: '1'
      sequence:
      - service: input_number.set_value
        data:
          value: 1
        target:
          entity_id: input_number.tesla_charge_state_fake
    - conditions:
      - condition: state
        entity_id: sensor.tesla_wall_connector_state
        state: '4'
      sequence:
      - service: input_number.set_value
        data:
          value: 4
        target:
          entity_id: input_number.tesla_charge_state_fake
    - conditions:
      - condition: state
        entity_id: sensor.tesla_wall_connector_state
        state: '9'
      sequence:
      - service: input_number.set_value
        data:
          value: 9
        target:
          entity_id: input_number.tesla_charge_state_fake
    - conditions:
      - condition: state
        entity_id: sensor.tesla_wall_connector_state
        state: '11'
      sequence:
      - service: input_number.set_value
        data:
          value: 11
        target:
          entity_id: input_number.tesla_charge_state_fake
    default:
    - service: input_number.set_value
      data:
        value: 99
      target:
        entity_id: input_number.tesla_charge_state_fake
  mode: queued
  max: 10
- id: '1700341762450'
  alias: office lights motion automation
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.office_pir_sensor_2
    to: 'on'
    enabled: true
  condition:
  - condition: not
    conditions:
    - condition: state
      entity_id: input_boolean.manual_lighting_override
      state: 'on'
    enabled: true
  action:
  - repeat:
      until:
      - condition: or
        conditions:
        - condition: state
          entity_id: binary_sensor.office_pir_sensor_2
          state: 'off'
          enabled: true
        - condition: state
          entity_id: input_boolean.manual_lighting_override
          state: 'on'
      sequence:
      - choose:
        - conditions:
          - condition: time
            before: 05:00:00
            after: 00:00:00
            weekday:
            - mon
            - tue
            - wed
            - thu
            - fri
            - sat
            - sun
          sequence:
          - service: light.turn_on
            data:
              rgb_color:
              - 255
              - 0
              - 0
              brightness: 153
            target:
              entity_id:
              - light.clone_strip_light
              - light.unified_pole_lights
          - service: light.turn_off
            data: {}
            target:
              entity_id:
              - light.clone_fan_light
              - light.clone_key_light
        - conditions:
          - condition: time
            before: '10:00:00'
            after: 05:00:00
            weekday:
            - mon
            - tue
            - wed
            - thu
            - fri
            - sat
            - sun
          sequence:
          - service: light.turn_on
            data:
              rgb_color:
              - 255
              - 255
              - 255
              brightness: 1
            target:
              entity_id:
              - light.unified_pole_lights
              - light.clone_strip_light
              - light.clone_fan_light
          - service: light.turn_off
            data: {}
            target:
              entity_id:
              - light.clone_key_light
        - conditions:
          - condition: time
            before: '17:30:00'
            after: '10:00:00'
            weekday:
            - mon
            - tue
            - wed
            - thu
            - fri
          sequence:
          - service: light.turn_on
            data:
              rgb_color:
              - 255
              - 255
              - 255
              brightness: 1
            target:
              entity_id:
              - light.unified_pole_lights
              - light.clone_strip_light
              - light.clone_fan_light
              - light.clone_key_light
          - service: light.turn_on
            data:
              brightness: 1
              kelvin: 5300
            target:
              entity_id:
              - light.clone_key_light
        - conditions:
          - condition: time
            before: '17:30:00'
            after: '10:00:00'
            weekday:
            - sat
            - sun
          sequence:
          - service: light.turn_on
            data:
              rgb_color:
              - 255
              - 255
              - 255
              brightness: 1
            target:
              entity_id:
              - light.unified_pole_lights
              - light.clone_strip_light
              - light.clone_fan_light
          - service: light.turn_off
            data: {}
            target:
              entity_id:
              - light.clone_key_light
        - conditions:
          - condition: time
            before: '20:00:00'
            after: '17:30:00'
            weekday:
            - mon
            - tue
            - wed
            - thu
            - fri
            - sat
            - sun
          sequence:
          - service: light.turn_on
            data:
              rgb_color:
              - 255
              - 255
              - 255
              brightness: 1
            target:
              entity_id:
              - light.unified_pole_lights
              - light.clone_strip_light
              - light.clone_fan_light
          - service: light.turn_off
            data: {}
            target:
              entity_id:
              - light.clone_key_light
        - conditions:
          - condition: time
            before: '23:59:59'
            after: '20:00:00'
            weekday:
            - mon
            - tue
            - wed
            - thu
            - fri
            - sat
            - sun
          sequence:
          - service: light.turn_on
            data:
              rgb_color:
              - 255
              - 255
              - 255
              brightness: 1
            target:
              entity_id:
              - light.unified_pole_lights
              - light.clone_strip_light
          - service: light.turn_off
            data: {}
            target:
              entity_id:
              - light.clone_key_light
              - light.clone_fan_light
      - delay:
          hours: 0
          minutes: 5
          seconds: 0
          milliseconds: 0
        enabled: true
  mode: restart
- id: '1700359934864'
  alias: no motion, lights off
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.office_pir_sensor_2
    to: 'off'
  condition: []
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.lights_off
    metadata: {}
  - service: input_boolean.turn_off
    data: {}
    target:
      entity_id: input_boolean.manual_lighting_override
  - service: input_boolean.turn_off
    data: {}
    target:
      entity_id: input_boolean.youtube_video_lighting
  - service: light.turn_off
    data: {}
    target:
      entity_id: light.unified_pole_lights
  mode: single
- id: '1700927611170'
  alias: youtube lighting
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_boolean.youtube_video_lighting
    from:
    to: 'on'
  condition: []
  action:
  - parallel:
    - service: input_boolean.turn_on
      data: {}
      target:
        entity_id: input_boolean.manual_lighting_override
    - service: light.turn_on
      data:
        rgb_color:
        - 255
        - 255
        - 255
        brightness_pct: 48
      target:
        entity_id:
        - light.clone_strip_light
        - light.unified_pole_lights
    - service: light.turn_on
      data:
        brightness_pct: 95
      target:
        entity_id: light.elgato_gw24l1a04995
    - service: light.turn_on
      data:
        rgb_color:
        - 255
        - 255
        - 255
        brightness_pct: 100
      target:
        entity_id: light.clone_fan_light
  mode: single
