esphome:
  name: office-motion
  friendly_name: office-motion

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "HJKLHJKLHJKLHJKLHJKLHJKLHJKLHJKLHJKL"

ota:
  password: "HJKLHJKLHJKLHJKLHJKLHJKLHJKLHJKLHJK"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: 192.168.1.61

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Office-Motion Fallback Hotspot"
    password: "HJKLHJKLHJKL"

captive_portal:

binary_sensor:
  - platform: gpio
    pin: 27
    name: "Office PIR Sensor"
    device_class: motion
    filters:
      - delayed_off: 300s
